### ISSUE TITLE
Running QCrBox With the Windows Store python on Windows 11

### ISSUE THREAD

**Issue by Niolon** [QCrBox/QCrBox#156]
Horst seems to have issues getting QCrBox container to build on Windows 11. Try on a separate machine whether that problem is reproducible

**Comment by maxalbert** [comment]
@mulomulo Can you provide the error message you are seeing?

**Comment by mulomulo** [comment]
There are no error messages. It tells us about the docker command it's about to execute, and that's when it stops. Copying the command manually will then actually work.

![image](https://github.com/QCrBox/QCrBox/assets/144746/2b50a886-807e-453d-820d-c690cba48376)

**Comment by mulomulo** [comment]
Or, as Niklas has put it: it is as if it was doing a dry run.

**Comment by Niolon** [comment]
As I wrote, I will try on my private Win11 notebook, whether I can reproduce that behaviour. I can do that probably sometime tomorrow.

**Comment by Niolon** [comment]
I can reproduce the issue on my Windows 11 machine, no idea what causes it

**Comment by maxalbert** [comment]
Good to hear that you can reproduce it! Just to check if this also happens with the latest version of the `dev` branch? I merged some changes which affect `qcb`. It would be a coincidence if they fixed this particular issue, but worth checking. ;)

**Comment by Niolon** [comment]
Test was with a fresh install that was cloned this morning

**Comment by maxalbert** [comment]
I tried to reproduce this on a Windows laptop and I _think_ I encountered the same (or at least a similar) bug. I just merged PR #166 which addresses the issue I saw. @Niolon @mulomulo Could you try again to see if this also resolves the problem you were seeing?

**Comment by Niolon** [comment]
Sorry, still no luck (but I see the difference between dry and non-dry execution), here are the commands and the output
```
(venv) PS C:\Coding\QCrBox\QCrBox> qcb up qcrboxtools -v
2024-25-66 00:03:21 | INFO     | Building Python package: qcrbox
------------------------------------ wheel ------------------------------------
(venv) PS C:\Coding\QCrBox\QCrBox> qcb up qcrboxtools -v -n
DRY-RUN | INFO     | Would build Python package: qcrbox
DRY-RUN | INFO     | Would pull/clone QCrBoxTools repo in C:\Coding\QCrBox\QCrBox\.build\QCrBoxTools ...
DRY-RUN | INFO     | Would build Python package: qcrboxtools
DRY-RUN | INFO     | Would build docker image: base-ancestor
DRY-RUN | DEBUG    | Would run docker compose command: 'docker compose --project-name=qcrbox --env-file=C:\\Coding\\QCrBox\\QCrBox\\.env.dev --file=C:\\Coding\\QCrBox\\QCrBox\\docker-compose.build.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\crystal_explorer\\docker-compose.crystal-explorer.build.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\eval1x\\docker-compose.eval1x.build.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\olex2_linux\\docker-compose.olex2_linux.build.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\qcrboxtools\\docker-compose.qcrboxtools.build.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\shelx\\docker-compose.shelx.build.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\xharpy_gpaw\\docker-compose.xharpy-gpaw.build.yml --file=C:\\Coding\\QCrBox\\QCrBox\\docker-compose.run.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\crystal_explorer\\docker-compose.crystal-explorer.run.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\eval1x\\docker-compose.eval1x.run.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\olex2_linux\\docker-compose.olex2_linux.run.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\qcrboxtools\\docker-compose.qcrboxtools.run.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\shelx\\docker-compose.shelx.run.yml --file=C:\\Coding\\QCrBox\\QCrBox\\services\\applications\\xharpy_gpaw\\docker-compose.xharpy-gpaw.run.yml build base-ancestor'
(venv) PS C:\Coding\QCrBox\QCrBox> qcb build pyqcrbox      
Building the following components (including dependencies): pyqcrbox

2024-26-66 00:03:22 | INFO     | Building Python package: qcrbox
------------------------------------ wheel ------------------------------------
(venv) PS C:\Coding\QCrBox\QCrBox> 
```

**Comment by maxalbert** [comment]
Hmm, things are working for me now so it's tricky to debug this without further information.

@Niolon Can I just confirm that if you delete the qcrbox wheel and then build pyqcrbox that the wheel will *not* be re-generated?
```
$ rm -f services/base_images/base_ancestor/qcrbox_dist/*.whl
$ qcb build -v pyqcrbox
```

**Comment by Niolon** [comment]
Sorry for the longer turnaround. The whl has not been generated (it is a fresh pull into a new folder)

**Comment by maxalbert** [comment]
Thanks! Can I ask a few more questions to better understand the context of the bug?

1. Are you running the commands from Powershell or from a Linux shell within WSL?
2. What Python distribution are you using / how did you install Python on the system?
3. What's the output of the following command?
    ```python -c "import sys; print(sys.executable); print(sys.version)"```

I'll also see if I can push a branch with a few more debugging messages so that we can get more information about what might be going wrong.

**Comment by mulomulo** [comment]
1) Powershell from within Visual Studio Code
2) Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) -- probably with an installer, but not sure
3) PS C:\Users\Horst\QCrBox> python -c "import sys; print(sys.executable); print(sys.version)"
C:\Users\Horst\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

**Comment by maxalbert** [comment]
@mulomulo Thanks! I think I have a lead. Could you run the following command as well and post the output please?
```
$ python -c "import shutil; print(shutil.which('docker')); print(shutil.which('docker.exe'))"
```

**Comment by mulomulo** [comment]
PS C:\Users\Horst\QCrBox> python -c "import shutil; print(shutil.which('docker')); print(shutil.which('docker.exe'))"
C:\Program Files\Docker\Docker\resources\bin\docker.EXE
C:\Program Files\Docker\Docker\resources\bin\docker.exe

**Comment by maxalbert** [comment]
@mulomulo I just merged some changes which will hopefully fix the issues you are seeing. Could you pull them and try again?

**Comment by mulomulo** [comment]
(venv) PS C:\Users\Horst\QCrBox> qcb up
Nothing to build. Consider using the --all flag or specify explicit component names.
(venv) PS C:\Users\Horst\QCrBox> qcb up olex2
2024-11-00 11:03:08 | INFO     | Building Python package: qcrbox
------------------------------------ wheel ------------------------------------
taskid:task_build_python_package:qcrbox - TaskFailed
Command failed: 'cd C:\Users\Horst\QCrBox\qcrbox && hatch build -t wheel C:\Users\Horst\QCrBox\services\base_images\base_ancestor\qcrbox_dist' returned 106

2024-11-00 11:03:53 | ERROR    | Execution of the command failed. See the logging output above for details.
(venv) PS C:\Users\Horst\QCrBox> qcb up --all
2024-12-00 11:03:98 | INFO     | Building Python package: qcrbox
------------------------------------ wheel ------------------------------------
taskid:task_build_python_package:qcrbox - TaskFailed
Command failed: 'cd C:\Users\Horst\QCrBox\qcrbox && hatch build -t wheel C:\Users\Horst\QCrBox\services\base_images\base_ancestor\qcrbox_dist' returned 106

**Comment by mulomulo** [comment]
After the latest updates (12.32) it's still the same for me:
(venv) PS C:\Users\Horst\QCrBox> qcb up --all
2024-36-00 12:03:15 | INFO     | Building Python package: qcrbox
------------------------------------ wheel ------------------------------------
taskid:task_build_python_package:qcrbox - TaskFailed
Command failed: 'cd C:\Users\Horst\QCrBox\qcrbox && hatch build -t wheel C:\Users\Horst\QCrBox\services\base_images\base_ancestor\qcrbox_dist' returned 106

2024-36-00 12:03:70 | ERROR    | Execution of the command failed. See the logging output above for details.

**Comment by maxalbert** [comment]
@mulomulo Does the latest change fix things for you?

**Comment by mulomulo** [comment]
('C:/Users/Horst/QCrBox/services/base_images/base_ancestor/qcrbox_dist')]' returned non-zero exit status 106.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Horst\QCrBox\venv\Lib\site-packages\doit\action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Horst\QCrBox\qcrbox\qcrbox\cli\subcommands\build.py", line 76, in action_build_qcrbox_wheel
    error_msg = prettyprint_called_process_error(exc)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Horst\QCrBox\qcrbox\qcrbox\cli\helpers\qcrbox_helpers.py", line 80, in prettyprint_called_process_error
    cmd = " ".join(exc.cmd)
          ^^^^^^^^^^^^^^^^^
TypeError: sequence item 4: expected str instance, WindowsPath found

**Comment by maxalbert** [comment]
The last commit should resolve this latest error. Hopefully this will bring us to the actual root cause of this issue...

**Comment by mulomulo** [comment]
(venv) PS C:\Users\Horst\QCrBox> qcb up --all
2024-40-00 13:03:34 | INFO     | Building Python package: qcrbox
───────────────────────────────────────────────────────────── wheel ──────────────────────────────────────────────────────────────
taskid:task_build_python_package:qcrbox - TaskError
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\Horst\QCrBox\qcrbox\qcrbox\cli\subcommands\build.py", line 74, in action_build_qcrbox_wheel
    proc.check_returncode()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['C:\\Users\\Horst\\QCrBox\\venv\\Scripts\\hatch.EXE', 'build', '-t', 'wheel', 'C:\\Users\\Horst\\QCrBox\\services\\base_images\\base_ancestor\\qcrbox_dist']' returned non-zero exit status 106.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Horst\QCrBox\venv\Lib\site-packages\doit\action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Horst\QCrBox\qcrbox\qcrbox\cli\subcommands\build.py", line 77, in action_build_qcrbox_wheel
    raise QCrBoxSubprocessError(error_msg)
qcrbox.cli.helpers.qcrbox_helpers.QCrBoxSubprocessError: An error occurred when executing the following command:

    C:\Users\Horst\QCrBox\venv\Scripts\hatch.EXE build -t wheel C:\Users\Horst\QCrBox\services\base_images\base_ancestor\qcrbox_dist

Return code: 106

Captured stdout:                         (not captured)
Captured stderr:                         (not captured)


2024-40-00 13:03:93 | ERROR    | Execution of the command failed. See the logging output above for details.

**Comment by mulomulo** [comment]
But maybe I am doing this all wrong. I get the changes and then 'pip install -e ./qcrbox[all]' -- then qcb up --all

**Comment by maxalbert** [comment]
@mulomulo Yup, that's the correct way to do it. Niklas has actually been reporting similar error to yours on Slack, so there is definitely something odd going on.

I pushed another change earlier that won't resolve the latest error but which should increase the debugging output. When you get a chance, could you pull and try one more time to see if it gives us any further clues? Thanks!

**Comment by Niolon** [comment]
I have a running version on Windows 11.

Solution
  1. Uninstall the Windows Store python version using the App uninstall of windows
  2. Get a new installer from python.org (the current version 3.12.2)
  3. Install. Activate support for long paths and add python to path
  4. Delete the venv folder and create a new one with the new python version
@mulomulo we should have a look whether this solves your issues as well. If it does we should add the instructions / a warning to the documentation

**Comment by Niolon** [comment]
Should be fixed by PR #178
